import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "@smastrom/react-rating/style.css";
import "./globals.css";
import { Rubik } from "next/font/google";

const rubik = Rubik({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className=" pt-10 px-5 lg:pt-24 lg:px-20 pb-10  bg-primary font-mona-sans">
          {children}
        </div>
      </body>
    </html>
  );
}
