import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "@smastrom/react-rating/style.css";
import "./globals.css";
import { Rubik } from "next/font/google";
import { TanstackProvider } from "@/providers/TanstackProvider";
import Navbar from "@/components/molecules/Navbar";
import { Toaster } from "@/components/ui";
import { MobileMenu } from "@/components/molecules";

const rubik = Rubik({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanstackProvider>
      <html lang="en">
        <head>
          <script
            type="text/javascript"
            src="https://app.sandbox.midtrans.com/snap/snap.js"
            data-client-key={process.env.NEXT_PUBLIC_MIDTRANS_SANDBOX_CLIENT_KEY}
          ></script>
        </head>
        <body className={rubik.className}>
          <Toaster />
          <Navbar />
          <MobileMenu />
          <div className="pt-32 px-5 lg:pt-24 lg:px-20 pb-10  bg-primary font-mona-sans">
            {children}
          </div>
        </body>
      </html>
    </TanstackProvider>
  );
}
